blog/urls.py
from django.urls import path
from . import views
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView
)


from django.contrib.auth import views as auth_views

urlpatterns = [
    path('home1/', PostListView.as_view(), name='blog-home'),
    path('houselist/', views.houselist, name='house-list'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
    path('register/', views.register1, name='register'),
    #path('loginnew/', views.loginUser, name='loginnew'),
     
    path('profile/', views.profile, name='profile'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='blog/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='blog/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='blog/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='blog/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    
    path('gallery/', views.gallery, name='gallery'),
    path('photo/<str:pk>/', views.viewPhoto, name='photo'),
    path('add/', views.addPhoto, name='add'),
    
    path('addtrip/', views.addTripDetails, name='addtrip'),
    path('dashboard/', views.Dashboard, name='dashboard'),
    path('updatetrip/<str:pk>', views.updateTripDetails, name='updatetrip'),
    path('deletetrip/<str:pk>', views.deleteTripDetails, name='deletetrip'),
    path('addvehicle/', views.addVehicleDetails, name='add_vehicle'),
    path('vehicle_details/<str:pk_vehicle>/', views.vehicleDetails, name="vehicle_details"),
    path('updatevehicle/<str:pk>', views.updateVehicleDetails, name='updatevehicle'),
    path('deletevehicle/<str:pk>', views.deleteVehicleDetails, name='deletevehicle'),
    
    path('addowner/', views.addOwnerDetails, name='add_owner'),
    path('owner_details/<str:pk_owner>/', views.ownerDetails, name="owner_details"),

    path('addvehiclepayment/', views.addVehiclePaymentDetails, name='add_vehicle_payment'),
    path('addvehiclepayment/<str:amount>', views.payVehiclePaymentDetails, name='pay_vehicle_payment'),
    path('addquarrypayment/', views.addQuarryPaymentDetails, name='add_quarry_payment'),
    path('addcompanypayment/', views.addCompanyPaymentDetails, name='add_company_payment'),
    path('addcompany/', views.addCompanyDetails, name='add_company'),
    path('addmaterial/', views.addLoadtypeDetails, name='add_material'),
    path('addquarry/', views.addQuarryDetails, name='add_quarry'),



    path('pdfroyaltybillimage/<str:pk_pdf>/', views.pdf_royalty_bill_image_view, name='pdf_royalty_bill_image'),
    path('pdfwaybillimage/<str:pk_pdf>/', views.pdf_way_bill_image_view, name='pdf_way_bill_image'),
    #path('pdfday/<str:pk_day>/', views.pdf_day_view, name='pdf_day'),
    path('pdfall/<str:pk_day>/', views.pdf_alldata_view, name='pdf_all'),
    path('pdfday/<str:pk_day>/', views.pdf_day_view, name='pdf_day'),
    path('', views.engineerView, name='engineer_page'),
    path('home/', views.engineerView, name='home_page'),
    path('billsgallery/', views.billsgallery, name='bills_gallery'),
    path('billphoto/<str:pk>/', views.billPhoto, name='gallery_bills_view'),
     

    

    path('initialadd/', views.layer1TripDetails, name='layer1add'),
    path('getpdfroyaltybillimage/<str:pk_pdf>/', views.get_pdf_royalty_bill_image_view, name='get_pdf_royalty_bill'),
    path('getpdfwaybillimage/<str:pk_pdf>/', views.get_pdf_way_bill_image_view, name='get_pdf_way_bill'),
    path('updatelayer1/<str:pk>', views.updatelayer1TripDetails, name='updatelayer1trip'),
    path('deletelayer1/<str:pk>', views.deletelayer1TripDetails, name='deletelayer1trip'),
    path('layer2add/<str:pk>/', views.layer2TripDetails, name='layer2add'),
    path('layer3add/<str:pk>/', views.layer3TripDetails, name='layer3add'),
    path('layer4add/<str:pk>/', views.layer4TripDetails, name='layer4add'),
    path('ajax/load-vehicles/', views.load_vehicle_numbers, name='ajax_load_vehicle_numbers'),


    path('dashboardnew/', views.dashboard_new, name='dashboard_new'),
    path('dailyvehicleownerreport/', views.daily_vehicle_owner_view, name='daily_vehicle_owner_report'),
    path('reports/', views.reports_view, name='reports_all'),
    path('dailygstinvoicereport/', views.daily_gst_invoice_view, name='daily_gst_invoice_report'),
    path('dailymaterialtypereport/', views.daily_material_type_view, name='daily_material_type_report'),
    path('dailymaterialtypereport_old/', views.daily_material_type_view_old, name='daily_material_type_report_old'),
    path('dailyquarryownerreport/', views.daily_quarry_onwer_view, name='daily_quarry_owner_report'),
    path('pdfdaytotal/<str:pk_day>/', views.pdf_day_total_view, name='pdf_day_total'),
    path('pdfdaygst/', views.pdf_day_gst_view, name='pdf_day_gst'),
    path('pdfdayreport/', views.pdf_day_report_view, name='pdf_day_report'),
    
]

postsproject/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='blog/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='blog/logout.html'), name='logout'),
    path('', include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from math import floor
from secrets import choice
from PIL import Image
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import RegexValidator


class District(models.Model):
    class Meta:
        verbose_name = 'District'
        verbose_name_plural = 'Districts'

    name = models.CharField(max_length=100, null=False, blank=False)
    housecount = models.IntegerField(null=False, blank=False)

    def __str__(self):
        return self.name
        
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='logo.png', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save( *args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


# Create your models here.


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.name


class Photo(models.Model):
    class Meta:
        verbose_name = 'Photo'
        verbose_name_plural = 'Photos'
    
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(null=False, blank=False)
    description = models.TextField()

    def __str__(self):
        return self.description

class TransporterDetails(models.Model):
    vehicle_owner_name = models.CharField(max_length=100, null=False, blank=False)
    phoneNumberRegex = RegexValidator(regex = r"^\+?1?\d{8,15}$")
    owner_phone_number = models.CharField(validators = [phoneNumberRegex], max_length = 16, null=False, blank=False)
    rate_per_tonne = models.CharField(max_length=200, null=True, blank=True)
    
    def __str__(self):
        return self.vehicle_owner_name

class VehicleDetails(models.Model):
    vehicle_number = models.CharField(max_length=10, null=False, blank=False)
    owner_name = models.ForeignKey(TransporterDetails, on_delete=models.SET_NULL, null=True, blank=False)
    phoneNumberRegex = RegexValidator(regex = r"^\+?1?\d{8,15}$")
    driver_name = models.CharField(max_length=200, null=True, blank=True)
    driver_phone_number = models.CharField(validators = [phoneNumberRegex], max_length = 16, null=True, blank=True)
    driver_name2 = models.CharField(max_length=200, null=True, blank=True)
    driver_phone_number2 = models.CharField(validators = [phoneNumberRegex], max_length = 16, null=True, blank=True)
    rate_per_tonne = models.CharField(max_length=200, null=False, blank=False)
    
    def __str__(self):
        return self.vehicle_number

class LoadType(models.Model):
    load_type = models.CharField(max_length=100, null=False, blank=False)
    load_type_rate_per_tonne = models.FloatField(null=False, blank=True)
    
    def __str__(self):
        return self.load_type

class CompanyName(models.Model):
    company_name = models.CharField(max_length=100, null=False, blank=False)

    
    def __str__(self):
        return self.company_name

class QuarryDetails(models.Model):
    quarry_owner_name = models.CharField(max_length=100, null=False, blank=False)
    quarry_ton_rate = models.FloatField(null=False, blank=True)
    
    def __str__(self):
        return self.quarry_owner_name

class TripDetails(models.Model):
    company_name = models.ForeignKey(CompanyName, on_delete=models.SET_NULL, null=True, blank=False)
    trip_date = models.DateField(null=False, blank=False)
    load_type = models.ForeignKey(LoadType, on_delete=models.SET_NULL, null=True, blank=False)
    quarry_owner_name = models.ForeignKey(QuarryDetails, on_delete=models.SET_NULL, null=True, blank=False)
    tf_number = models.CharField(max_length=200, null=False, blank=False)
    qty_m3 = models.FloatField(null=False, blank=False)
    vehicle_number = models.ForeignKey(
        VehicleDetails , on_delete=models.SET_NULL, null=True, blank=False)
    qty_ton = models.FloatField(null=False, blank=False)
    royalty_image = models.ImageField(null=False, blank=False)
    waybill_image = models.ImageField(null=False, blank=False)

class InitialTripDetails(models.Model):
    trip_date = models.DateField(null=False, blank=False)
    company_name = models.ForeignKey(CompanyName, on_delete=models.SET_NULL, null=True, blank=False)
    vehicle_number = models.ForeignKey(
        VehicleDetails , on_delete=models.SET_NULL, null=True, blank=False)
    driver_name = models.ForeignKey(
        TransporterDetails , on_delete=models.SET_NULL, null=True, blank=False)
    quarry_owner_name = models.ForeignKey(QuarryDetails, on_delete=models.SET_NULL, null=True, blank=False)
    load_type = models.ForeignKey(LoadType, on_delete=models.SET_NULL, null=True, blank=False)
    tf_number = models.CharField(max_length=200, null=False, blank=False)
    qty_m3 = models.FloatField(null=False, blank=False)
    royalty_image_front = models.ImageField(null=False, blank=False)
    royalty_image_back = models.ImageField(null=False, blank=True)

class Layer2TripDetails(models.Model):
    Yes = 1
    No = 2
    STATUS = (
       (Yes, ('Confirm Send')),
       (No, ('No, require more time')),
   )
    
    trip_date = models.DateField(null=False, blank=False)
    company_name = models.ForeignKey(CompanyName, on_delete=models.SET_NULL, null=True, blank=False)
    vehicle_number = models.ForeignKey(
        VehicleDetails , on_delete=models.SET_NULL, null=True, blank=False)
    driver_name = models.ForeignKey(
        TransporterDetails , on_delete=models.SET_NULL, null=True, blank=False)
    quarry_owner_name = models.ForeignKey(QuarryDetails, on_delete=models.SET_NULL, null=True, blank=False)
    load_type = models.ForeignKey(LoadType, on_delete=models.SET_NULL, null=True, blank=False)
    tf_number = models.CharField(max_length=200, null=False, blank=False)
    qty_m3 = models.FloatField(null=False, blank=False)
    royalty_image_front = models.ImageField(null=False, blank=False)
    royalty_image_back = models.ImageField(null=False, blank=True)
    qty_ton = models.FloatField(null=False, blank=False)
    waybill_image_front = models.ImageField(null=False, blank=False)
    waybill_image_back = models.ImageField(null=False, blank=True)
    sendtomalli = models.PositiveSmallIntegerField(
       choices=STATUS,
       default=Yes,
   )



STATUS = [
       ('Yes', 'Data is Correct, Send Forward'),
       ('No', 'Data is wrong, Send Back'),
    ]
VERIFY = [
       ('Yes', 'Data is Correct, Verify'),
       ('No', 'Data is wrong, Send back'),
    ]
COMMENTS = [
        ('no comments', 'None'),
        ('trip started', 'Trip Started'),
        ('trip completed', 'Trip Completed'),
        ('trip approved', 'Trip Approved'),
        ('trip verified', 'Trip Verified'),
        ('m3 wrong', 'M3 Wrong'),
        ('tf number wrong', 'TF Number Wrong'),
        ('ton wrong', 'Ton Wrong'),
]
class LayerWiseTripDetails(models.Model): 
    trip_date = models.DateField(null=False, blank=False,default='2022-03-20')
    company_name = models.ForeignKey(CompanyName, on_delete=models.SET_NULL, null=True, blank=False)
    
    vehicle_owner_name = models.ForeignKey(
        TransporterDetails , on_delete=models.SET_NULL, null=True, blank=False)
    vehicle_number = models.ForeignKey(
        VehicleDetails , on_delete=models.SET_NULL, null=True, blank=False)
    driver_name = models.CharField(max_length=200,null=True, blank=False)
    quarry_owner_name = models.ForeignKey(QuarryDetails, on_delete=models.SET_NULL, null=True, blank=False)
    load_type = models.ForeignKey(LoadType, on_delete=models.SET_NULL, null=True, blank=False)
    tf_number = models.CharField(max_length=200, null=False, blank=False)
    qty_m3 = models.FloatField(null=False, blank=False)
    royalty_image_front = models.ImageField(null=False, blank=False)
    #royalty_image_back = models.ImageField(null=False, blank=True)
    qty_ton = models.FloatField(null=False, blank=False, default=0.0)
    waybill_image_front = models.ImageField(null=False, blank=False)
    waybill_image_back = models.ImageField(null=False, blank=True)
    #verifiedbyengineer = models.CharField(max_length=200, blank=False, null=False, choices=STATUS, default='No')
    #verifiedbymalli = models.CharField(max_length=200, blank=False, null=False, choices=STATUS, default='No')
    qty_ton = models.FloatField(null=False,default=0, blank=False)
    waybill_image_front = models.ImageField(default='logo.png',null=False, blank=False)
    waybill_image_back = models.ImageField( null=False, blank=True)
    #verifiedbysuresh = models.CharField(max_length=200, blank=False, null=False, choices=VERIFY, default='No')
    comments = models.CharField(max_length=200, blank=True, null=True, choices=COMMENTS, default='none')
    forwarded = models.CharField(max_length=200, blank=True, null=True, default='Deny')
    approved = models.CharField(max_length=200, blank=True, null=True,  default='Deny')
    verified = models.CharField(max_length=200, blank=True, null=True,  default='Deny')

    @property
    def qty_m3_actual_submit(self):
        return round(self.qty_ton/1.5,2)
    @property

blog/templates/blog/add_quarry_details.html
{% extends "blog/base.html" %}
{% block content %}
{% load crispy_forms_tags %}


<head>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
<style>
.card{
    width: 850px;
    box-shadow: rgb(0 0 0 / 24%) 0px 3px 8px;
    margin-top: 20px;
    margin-left: -25px;
    
}
.form-group {
    margin-bottom: 1rem;
    width: 315px;
    float: left;
    / padding: 5px; /
    margin-top: -15px;
    padding-right: 25px;
}

.animation-form{
    animation: fadeInRight;
    animation-duration: 2s; 
   
}
.fieldWrapper{
    
    /* width: 390px;
    float: left;
    padding: 20px;
    height: 100px; */
}
.btn-submit-init{
    width: 120px;
    height: 40px;
    float: left;
    color: white;
    background-color: #0069D9;
    border-radius: 5px;
    border: 1px solid whitesmoke;

}
.btn-close-init{
    width: 120px;
    background: gray;
    color: white;
    margin-left: 20px;
}
.header-text1{
    height: 50px;
    background-color: #009BDA;
    color: white;
    text-align: center;
    margin-top: -20px;
    width: 848px;
    margin-left: -20px;
}
.text1{
    color: white;
    line-height: 44px;
    font-size: 24px;
}
.btn-submit-addpay{
    width: 120px;
    height: 40px;
    float: left;
    color: white;
    background-color: #0069D9;
    border-radius: 5px;
    border: 1px solid whitesmoke;

}
.btn-close-addpay{
    width: 120px;
    background: gray;
    color: white;
    margin-left: 20px;
}



</style>



  </head>

<body class="m-5">
    <div class="container">
      <div class="row"> 
            <div class="col-md-12 animation-form">
                <div class="card card-body ">

                     <div class="header-text1">
                        <p class="text1">Add Quarry Details</p>
                    </div> 
                    <!--------form------start-->
                    <form action="" method="POST" enctype="multipart/form-data" style="margin-left: 98px;margin-right:75px;margin-top:20px">
                       
                            {% csrf_token %}
                            {{form | crispy }}
                            <br>
                            <input type="submit" name="Submit" class="btn-submit-addpay" style="margin-left: 0px;">
                            <a class="btn btn-outline-secondary btn-close-addpay" href="{% url 'engineer_page'  %}">Cancel</a>
                        </form>
                <!---------form-------end----------------->

                </div>
            </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    
  <script>
    
    $("#id_vehicle_owner_name").change(function () {
        var url = $("#personForm").attr("data-vehicle-numbers-url"); // get the url of the `load_cities` view
        var countryId = $(this).val(); // get the selected country ID from the HTML input
        console.log(countryId)
        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
            'countryid': countryId       // add the country id to the GET parameters
            },
            success: function (data) {
                console.log(data)   // `data` is the return of the `load_cities` view function
            $("#id_vehicle_number").html(data);  // replace the contents of the city input with the data that came from the server
            }
      });

    });

  </script>  
 

{% endblock %}  
</body>

blog/templates/blog/base_new.html
{% load static %}
{% load crispy_forms_tags %}
  
<!DOCTYPE html>
<html>
<head>
    <!----------font awesome--------->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

    {% if title %}
        <title>Django Blog - {{ title }}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}


    
    <style>
      .list-group{
        overflow: auto;
        width: 312px;
        height: 200px;
      }
     
      label {
          display: inline-block;
          margin-bottom: 0.5rem;
          font-size: 12px;
          font-weight: bold;
      }
      /* .modal-body {
          
          padding-left: 50px !important;
          padding-right: 50px !important;
          padding-bottom: 30px !important;
      } */
      .oursidebar{
        margin-top: 20px !important;
        box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
          
      }
      .left-card{
         
          margin-top: 20px;
          box-shadow: rgb(0 0 0 / 24%) 0px 3px 8px;
         
      }
      .left-sidebar{
        position: fixed;
        top: 140px;
        width: 345px;
        box-shadow: rgb(0 0 0 / 24%) 0px 3px 8px;
      }
      .card2{
        padding: 15px;
        background-color: white;
        border-radius: 3px;
        /* height: 290px; */
      }
     table,th,td{
       border: 1px solid #dbd0d0 !important;
     };
      
    
      </style>





</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a hidden class="navbar-brand mr-4" href="{% url 'engineer_page' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'engineer_page' %}">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container" style="margin: 0px !important;">
      <div class="row mb-5">
        
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        
      </div>
     

    </main>

    <script type="text/javascript">
          // Data Picker Initialization
          $('#trip_date').datepicker({
          format: 'dd-mm-yyyy (D)',
          autoclose: true,
          keyboardNavigation : true ,
          endDate : dateFormat(date, "dd-mm-yyyy (ddd)"),
          daysOfWeekDisabled : [0]
      });
    </script>
 

    <!-- Optional JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
                                                    

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>








</body>
</html>

blog/templates/blog/delete_vehicle_details.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Selected details</legend>
                <h2>Are you sure you want to delete these details ?</h2>
                <div class="col-md">
                    <div class="card card-body">
                        <h5>{{ delete_vehicle_detail.vehicle_number }} vehicle details:</h5>
                        <hr>
                        <p>Owner name : {{delete_vehicle_detail.owner_name}}</p>
                        <p>Phone number : {{delete_vehicle_detail.phonenumber}}</p>
                        <p>Driver name : {{delete_vehicle_detail.driver_name}}</p>
                        <p>Phone number : {{delete_vehicle_detail.driver_phonenumber}}</p>
            
                    </div>
                </div>
            
                <div class="col-md">
                    <div class="card card-body">
                        <h5 >Billing Information</h5>
                        <hr>
                        <p>Rate per Ton : {{delete_vehicle_detail.rate_per_tonne}}</p>
            
            
                    </div>
                </div>   
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'home_page'  %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}